Still trying to get test-coverage workflow to work on GitHub
The step codecov/codecov-action@v4 fails on GitHub with error:

"info - 2025-01-03 19:02:52,761 -- ci service found: github-actions
warning - 2025-01-03 19:02:52,797 -- Branch `main` is protected but no token was provided
warning - 2025-01-03 19:02:52,797 -- For information on Codecov upload tokens, see https://docs.codecov.com/docs/codecov-tokens
info - 2025-01-03 19:02:53,146 -- Process Commit creating complete
error - 2025-01-03 19:02:53,146 -- Commit creating failed: {"message":"Token required because branch is protected"}
Error: Codecov: Failed to properly create commit: The process '/Users/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1"

I don't want to commit to codecov anyways because CSAFE doesn't have an account, so I tried deleting this step.